### ISSUE TITLE
Reduce Wallet Unlocked Timeout

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq2#52]
At the moment the default wallet timeout (wallet unlocked) is set to 24 hours. We have to reduce it later to something like 5 minutes.
https://github.com/bisq-network/bisq2/blob/2b6a99ed7b33b51f4cd13c09842800c4b46c7bf9/wallets/src/main/java/bisq/wallets/bitcoind/BitcoindWalletBackend.java#L17
#### Tasks
- [x] Identify RPC Calls that need wallet to be unlocked
- [x] Unlock wallet before making RPC call (if locked)
- [x] Lock wallet after RPC call
